// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCvoqeFT0jaPB8h4nufCp2q_nJFxdmxAc',
    appId: '1:525745601276:web:555311f3ae508fc6eef579',
    messagingSenderId: '525745601276',
    projectId: 'bootcamp-bce8c',
    authDomain: 'bootcamp-bce8c.firebaseapp.com',
    storageBucket: 'bootcamp-bce8c.appspot.com',
    measurementId: 'G-VJKC008ZQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDl50tecr3bwjEyXptCNJG78CECSqQWIo',
    appId: '1:525745601276:android:6fa1b086b16d8206eef579',
    messagingSenderId: '525745601276',
    projectId: 'bootcamp-bce8c',
    storageBucket: 'bootcamp-bce8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0BcQL76_hxGIyy9yhLSbr4ynzJonMi9I',
    appId: '1:525745601276:ios:0f151eff20fc8851eef579',
    messagingSenderId: '525745601276',
    projectId: 'bootcamp-bce8c',
    storageBucket: 'bootcamp-bce8c.appspot.com',
    iosBundleId: 'com.example.bootcamp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0BcQL76_hxGIyy9yhLSbr4ynzJonMi9I',
    appId: '1:525745601276:ios:0f151eff20fc8851eef579',
    messagingSenderId: '525745601276',
    projectId: 'bootcamp-bce8c',
    storageBucket: 'bootcamp-bce8c.appspot.com',
    iosBundleId: 'com.example.bootcamp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCvoqeFT0jaPB8h4nufCp2q_nJFxdmxAc',
    appId: '1:525745601276:web:f8dadf5ecd53843beef579',
    messagingSenderId: '525745601276',
    projectId: 'bootcamp-bce8c',
    authDomain: 'bootcamp-bce8c.firebaseapp.com',
    storageBucket: 'bootcamp-bce8c.appspot.com',
    measurementId: 'G-HVB0HN6DE1',
  );
}
